name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*-canary.*

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_REMOTE_CACHE_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_REMOTE_CACHE_TEAM }}
  TURBO_LOG_ORDER: stream

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    timeout-minutes: 2

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get monorepo release version
        id: get-version
        run: |
          version=v$(jq -r '.version' package.json)
          echo "version=$version" >> $GITHUB_OUTPUT

  release-to-github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs:
      - prepare-release
    timeout-minutes: 2

    environment: GitHub

    permissions:
      contents: write

    steps:
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.prepare-release.outputs.version }}
          tag: ${{ needs.prepare-release.outputs.version }}
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: ${{ startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main' }}
          allowUpdates: ${{ !(startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main') }}
          replacesArtifacts: ${{ !(startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main') }}
          prerelease: ${{ !(startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main') }}
          generateReleaseNotes: true
